<?php
    if ($type == "jpeg") {
        $stype = "jpg";
    } else {
        $stype = $type;
    }
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title><?php echo APP_NAME . " - $file.$stype"; ?></title>
        <link rel="stylesheet" href="/assets/css/style.css">
    </head>

    <body>
        <h1><?php echo "$file.$type"; ?> &middot; <abbr title="Value rounded to the nearest kb.">~<?php echo round($filesize / 1024, 0); ?>kb</abbr></h1>

        <div class="container">
            <img src="/images/<?php echo "$type/$file.$stype"; ?>" alt="<?php echo "$file.$stype"; ?>">
        </div>

        <?php
            $time = microtime();
            $time = explode(' ', $time);
            $time = $time[1] + $time[0];
            $finish = $time;
            $total_time = round(($finish - $start), 4);
        ?>

        <p><a href="https://github.com/aerouk/imageserve">Powered by <b>imageserve</b></a> &middot; Page generated in <?php echo $total_time; ?> seconds</p>
    </body>
</html>
